microserviceName: "identity"

image:
  repository: dublinhouse.azurecr.io/play.identity
  tag: 1.0.10

envVariables:
  IdentitySettings__PathBase: /identity-svc
  IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
  IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"
  IdentityServerSettings__Clients__0__RedirectUris__0: https://dublinhouse.eastus.cloudapp.azure.com/authentication/login-callback
  IdentityServerSettings__Clients__0__PostLogoutRedirectUris__0: https://dublinhouse.eastus.cloudapp.azure.com/authentication/logout-callback

container:
  port: 5002
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates    

volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

certificate:
  secretName: signing-cert
  hostname: dublinhouse.eastus.cloudapp.azure.com

identityClientId: 60a5138a-e007-46b9-b06f-8d69cd360211